# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    logos_directory : '%kernel.project_dir%/public/template/logo'
    notes_attachments_directory : '%kernel.project_dir%/public/template/notes'
    secure_files_attachments_directory : '%kernel.project_dir%/public/template/secureFiles'
    app.locales : ['en', 'fr', 'es', 'de']
    default_locale: '%app.locales%'
    app.timezone: 'GMT'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    App\Form\EventSubscriber\FormSanitizeSubscriber:
        arguments:
            - '@App\Service\HtmlSanitizer'
        public: true
    App\Service\SecureEncryptionService:
        bind:
            $key: '%env(APP_ENCRYPTION_KEY_DOCS)%'
    App\Service\PdfGeneratorService: ~
    App\Controller\SecureFilesController:
        bind:
            $encryptionKeyAad: '%env(APP_ENCRYPTION_KEY_AAD)%'
    App\Service\EncryptionService:
        bind:
            $key: '%env(APP_ENCRYPTION_KEY)%'
    App\Command\BurnExpiredNotesCommand:
        arguments:
            $attachmentsDirectory: '%notes_attachments_directory%'

    

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
